name: emergent_communication
channels:
  - defaults
dependencies:
  - entrypoints
  - ipython
  - colorama
  - cryptography
  - ipywidgets
  - sqlite=3.37.2
  - mkl_fft
  - brotlipy
  - tqdm
  - cffi
  - argon2-cffi
  - cudatoolkit=10.2.89
  - jinja2=2.11.2
  - numpy-base
  - libuuid=1.0.3
  - ld_impl_linux-64=2.35.1
  - pyasn1-modules
  - future
  - readline=8.1.2
  - editdistance
  - tornado
  - gstreamer=1.14.0
  - markdown
  - oauthlib
  - pyrsistent
  - blas=1.0
  - openssl
  - scikit-learn
  - idna
  - importlib-metadata
  - terminado
  - pandocfilters
  - async-timeout
  - libffi=3.3
  - pytz
  - attrs
  - freetype=2.10.4
  - jupyter_console
  - blinker
  - glib=2.56.2
  - tzdata=2021e
  - icu=58.2
  - ca-certificates
  - mkl-service
  - jpeg=9b
  - debugpy
  - libstdcxx-ng=9.3.0
  - libgfortran-ng=7.5.0
  - charset-normalizer
  - tensorboard
  - python_abi
  - pysocks
  - pyparsing
  - prompt-toolkit
  - bleach
  - libgcc-ng=9.3.0
  - markupsafe
  - pyjwt
  - backcall
  - rsa
  - wheel
  - jupyter
  - pyyaml
  - nbformat
  - cachetools
  - click
  - pandoc=2.11
  - _libgcc_mutex=0.1
  - notebook
  - libgomp=9.3.0
  - libpng=1.6.37
  - aiohttp
  - yarl
  - ipykernel
  - six
  - libprotobuf=3.15.8
  - pyopenssl
  - scipy=1.7.3
  - libuv=1.40.0
  - libxml2=2.9.10
  - packaging
  - webencodings
  - google-auth-oauthlib
  - dbus=1.13.18
  - tensorboard-data-server
  - traitlets
  - jupyter_core
  - fontconfig=2.13.0
  - qtconsole
  - decorator
  - mistune
  - threadpoolctl
  - multidict
  - pip
  - argon2-cffi-bindings
  - mkl=2021.4.0
  - google-auth
  - absl-py
  - c-ares=1.18.1
  - sip
  - pyasn1
  - pyqt
  - mkl_random
  - matplotlib-inline
  - python-dateutil
  - prometheus_client
  - libgfortran4=7.5.0
  - libsodium=1.0.18
  - jupyter_client
  - pexpect
  - expat=2.2.10
  - urllib3
  - xz=5.2.5
  - ptyprocess
  - zeromq=4.3.4
  - pyu2f
  - werkzeug
  - testpath
  - chardet
  - widgetsnbextension
  - defusedxml
  - intel-openmp=2021.4.0
  - prompt_toolkit
  - pandas
  - _openmp_mutex=4.5
  - jsonschema
  - pygments
  - grpcio
  - pickleshare
  - fsspec
  - protobuf
  - python=3.9.7
  - qtpy
  - nbconvert
  - zlib=1.2.11
  - joblib
  - pcre=8.44
  - wcwidth
  - certifi
  - requests-oauthlib
  - yaml=0.2.5
  - parso
  - tk=8.6.11
  - ncurses=6.3
  - tensorboard-plugin-wit
  - requests
  - zipp
  - qt=5.9.7
  - numpy
  - pycparser
  - ipython_genutils
  - send2trash
  - pyzmq
  - jedi
  - libxcb=1.14
  - gst-plugins-base=1.14.0
  - h5py
  - pytorch
  - torchaudio
  - pytorch-cuda=11.7
  - torchvision
  - torchmetrics
