name: emergent_communication
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.7.4.post0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-timeout=3.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cachetools=5.0.0
  - certifi=2022.9.14
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - colorama=0.4.4
  - cpuonly=2.0
  - cryptography=35.0.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.1.0
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.56.2
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.1
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9e
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.9.1
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - nbconvert=5.5.0
  - nbformat=5.0.8
  - ncurses=6.3
  - notebook=6.4.5
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.2.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.11
  - pandocfilters=1.5.0
  - parso=0.8.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.15.8
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.7.1
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-lightning=1.6.3
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.2
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.13.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.11
  - torchmetrics=0.7.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.0.5
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - numexpr==2.8.3
    - pandas==1.4.4
    - tbparse==0.0.7
