model:
  baseline_type: mean
  length_cost: 0.0
  max_len: 5
  num_features: 10
  num_values: 2
  receiver_embed_dim: 10
  receiver_num_layers: 1
  receiver_hidden_dim: 32
  sender_embed_dim: 10
  sender_entropy_coeff: 0.1
  sender_num_layers: 1
  sender_hidden_dim: 32
  vocab_size: 10
  log_topsim_on_validation: false
trainer:
  val_check_interval: 1000
  log_every_n_steps: 100
  limit_train_batches: 100000
#  reload_dataloaders_every_n_epochs: 1
data:
  batch_size: 64
  num_distractors: 4
  num_workers: 8
