seed: 1
model:
  symmetric: false
  optimal_sender: false
  alt_agents: false
  load_checkpoint: null
  baseline_type: mean
  length_cost: 0
  max_len: 4  # Excluding EOS token!
  num_features: 4
  num_values: 4
  num_senders: 1
  num_receivers: 1
  receiver_embed_dim: 30
  receiver_num_layers: 1
  receiver_hidden_dim: 500
  receiver_learning_speed: 1
  receiver_aux_loss: false
  receiver_aux_loss_2: false
  receiver_aux_loss_3: false
  sender_aux_loss: false
  sender_aux_loss_2: false
  sender_embed_dim: 5
  sender_entropy_coeff: 0.5
  receiver_entropy_coeff: 0.5
  sender_num_layers: 1
  receiver_layer_norm: false  # Currently not implemented!
  sender_layer_norm: false  # Currently not implemented!
  sender_hidden_dim: 500
  sender_learning_speed: 1
  vocab_size: 5 # Including the EOS token!
  noise: 0
  multi_turn: false
  open_cr: false
  log_topsim_on_validation: false
  log_posdis_on_validation: false
  log_bosdis_on_validation: false
  log_entropy_on_validation: false
trainer:
  default_hp_metric: false
  max_epochs: 100000
  check_val_every_n_epoch: 100
  log_every_n_steps: 1000
  num_sanity_val_steps: 3
  gpus: 0
data:
  max_num_objects: 100000
  batch_size: 5120
  test_set_size: 0.1
  num_workers: 0