seed: 1
model:
  symmetric: false
  optimal_sender: false
  baseline_type: mean
  length_cost: 0.0
  max_len: 5
  speech_acts: [REQUEST, QUESTION_FORALL, QUESTION_EXISTS]
  num_features: 4
  num_values: 4
  num_senders: 1
  num_receivers: 1
  receiver_embed_dim: 128
  receiver_num_layers: 1
  receiver_hidden_dim: 128
  receiver_learning_speed: 1
  receiver_aux_loss: true
  sender_embed_dim: 128
  sender_entropy_coeff: 0.1
  sender_num_layers: 1
  receiver_layer_norm: true
  sender_layer_norm: true
  sender_hidden_dim: 128
  sender_learning_speed: 1
  vocab_size: 10
  log_topsim_on_validation: false
  log_entropy_on_validation: false
trainer:
  val_check_interval: 100
  log_every_n_steps: 25
  limit_val_batches: 10
  limit_train_batches: 100000
  num_sanity_val_steps: 3
  gpus: 0
data:
  max_num_objects: 100000
  batch_size: 512
  num_objects: 2
  test_set_size: 0.1
  num_workers: 0