seed: 1
model:
  symmetric: false
  optimal_sender: false
  alt_agents: true
  baseline_type: mean
  length_cost: 0.0
  max_len: 5
  num_features: 4
  num_values: 4
  num_senders: 1
  num_receivers: 1
  receiver_embed_dim: 128
  receiver_num_layers: 1
  receiver_hidden_dim: 512
  receiver_learning_speed: 1
  receiver_aux_loss: true
  sender_embed_dim: 128
  sender_entropy_coeff: 0.1
  receiver_entropy_coeff: 0.1
  sender_num_layers: 1
  receiver_layer_norm: true
  sender_layer_norm: true
  sender_hidden_dim: 512
  sender_learning_speed: 1
  vocab_size: 5
  noise: 0.0
  multi_turn: false
  log_topsim_on_validation: true
  log_entropy_on_validation: false
trainer:
  default_hp_metric: false
  max_epochs: 100000
  check_val_every_n_epoch: 100
  log_every_n_steps: 2
  num_sanity_val_steps: 3
  gpus: 0
data:
  max_num_objects: 100000
  batch_size: 128
  test_set_size: 0.2
  num_workers: 0