accelerator: gpu
accumulate_grad_batches: null
amp_backend: null
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
baseline_type: mean
batch_size: 1000
benchmark: null
check_val_every_n_epoch: 20
default_root_dir: null
detect_anomaly: false
devices: null
discrimination_num_objects: 10
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
feedback: false
gpus: null
grad_clip: 1
gradient_clip_algorithm: null
gradient_clip_val: null
guesswhat: true
hard_distractors: false
imagenet: false
inference_mode: true
initial_lr: 0.001
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: 100
load_checkpoint: null
log_bosdis_on_validation: false
log_entropy_on_validation: false
log_every_n_steps: 50
log_every_steps: 10000
log_posdis_on_validation: false
log_topsim_on_validation: false
logger: true
max_epochs: -1
max_len: 20
max_num_objects: 100000
max_steps: -1
max_time: 00:10:00:00
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
noise: 0.1
noise_permutation: false
num_attributes: 4
num_nodes: 1
num_processes: null
num_receivers: 1
num_sanity_val_steps: 3
num_senders: 1
num_values: 4
num_workers: 4
optimal_sender: false
overfit_batches: 0.0
patience: 100
plugins: null
precision: 16
profiler: null
receiver_attn_method: general
receiver_aux_loss: false
receiver_embed_dim: 16
receiver_entropy_coeff: 0.01
receiver_hidden_dim: 128
receiver_layer_norm: true
receiver_learning_speed: 1
receiver_num_layers: 1
receiver_object_attention: false
receiver_output_attention: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
reset_parameters: false
reset_parameters_fraction: 0.9
reset_parameters_interval: 1
resume_from_checkpoint: null
seed: 1
sender_attention: false
sender_attn_method: dot
sender_embed_dim: 16
sender_entropy_coeff: 0.01
sender_hidden_dim: 128
sender_layer_norm: true
sender_learning_speed: 1
sender_num_layers: 1
stopping_threshold: 0.99
strategy: null
symmetric: false
sync_batchnorm: false
test_set_size: 0.0
tpu_cores: null
track_grad_norm: -1
update_masks: false
val_check_interval: null
val_set_size: 0.1
vocab_size: 2
vocab_size_feedback: 2
